# Generated by Django 3.1.5 on 2021-02-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='手机')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='zufang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15, verbose_name='城市')),
                ('date', models.DateField(null=True, verbose_name='日期')),
                ('district', models.CharField(max_length=20, verbose_name='区域')),
                ('area', models.CharField(max_length=20, verbose_name='小区')),
                ('form', models.CharField(max_length=15, verbose_name='出租类型')),
                ('village', models.CharField(max_length=20, verbose_name='房屋')),
                ('item', models.CharField(max_length=20, verbose_name='房屋类型')),
                ('direction', models.CharField(max_length=5, verbose_name='房屋朝向')),
                ('size', models.CharField(max_length=15, verbose_name='房屋大小')),
                ('price', models.CharField(max_length=10, verbose_name='价格')),
            ],
        ),
    ]
