# Generated by Django 3.1.5 on 2021-02-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210207_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='邮箱'),
        ),
    ]
