# Generated by Django 3.1.5 on 2021-02-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210210_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
