# Generated by Django 3.1.5 on 2021-02-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('password', models.CharField(max_length=256)),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='手机')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='邮箱')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['createTime'],
            },
        ),
    ]
