# Generated by Django 3.1.5 on 2021-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210320_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('collection', models.CharField(max_length=2000, verbose_name='收藏')),
                ('count', models.IntegerField(default=0, verbose_name='收藏数')),
            ],
        ),
    ]
